/**

 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */

const fs = require("fs");
const express = require("express");
const app = express();

const hikeData = [
  {
    id: 1,

    imagePath: "/images/tommhoi.jpeg",
    name: "Grouse Grind Proper",
    city: "North Vancouver",
    province: "British Columbia",
    distance: "3.2km",
    elevation: "867m",
    difficulty: "Hard",
  },
  {
    id: 2,
    imagePath: "/images/golden-ears.jpeg",
    name: "Golden Ears Summit",
    city: "Maple Ridge",
    province: "British Columbia",
    distance: "26km",
    elevation: "1800m",
    difficulty: "Hard",
  },
  {
    id: 3,
    imagePath: "/images/mount-macfarlane.jpeg",
    name: "Wedgemount Lake",
    city: "Whistler",
    province: "British Columbia",
    distance: "12km",
    elevation: "1160m",
    difficulty: "Hard",
  },
  {
    id: 4,
    imagePath: "/images/elk-mount.jpeg",
    name: "Elk Mountain",
    city: "Chilliwack",
    province: "British Columbia",
    distance: "7km",
    elevation: "800m",
    difficulty: "Medium",
  },
  {
    id: 5,
    imagePath: "/images/joffre-amin.jpeg",
    name: "Joffre Lakes",
    city: "Pemberton",
    province: "British Columbia",
    distance: "10km",
    elevation: "370m",
    difficulty: "Easy",
  },
  {
    id: 6,
    imagePath: "/images/deeks-lake.jpeg",
    name: "Saint Mark's Summit",
    city: "West Vancouver",
    province: "British Columbia",
    distance: "10km",
    elevation: "570m",
    difficulty: "Medium",
  },
  {
    id: 7,
    imagePath: "/images/crown-mountain.jpeg",
    name: "Garibaldi Lake",
    city: "Whistler",
    province: "British Columbia",
    distance: "18.2km",
    elevation: "979m",
    difficulty: "Medium",
  },
  {
    id: 8,
    imagePath: "/images/spencers-peak.jpeg",
    name: "The Lions Binkert Trail",
    city: "West Vancouver",
    province: "British Columbia",
    distance: "16km",
    elevation: "1280m",
    difficulty: "Hard",
  },
  {
    id: 9,
    imagePath: "/images/three-brothers.jpeg",
    name: "Al's Habrich Ridge Trail",
    city: "Howe Sound",
    province: "British Columbia",
    distance: "7km",
    elevation: "440m",
    difficulty: "Easy",
  },
  {
    id: 10,
    imagePath: "/images/crown-mountain.jpeg",
    name: "Elfin Lakes",
    city: "Garibaldi Provincial Park",
    province: "British Columbia",
    distance: "22km",
    elevation: "600m",
    difficulty: "Medium",
  },
  {
    id: 11,
    imagePath: "/images/sea-to-sky.jpeg",
    name: "Stawamus Chief",
    city: "Squamish",
    province: "British Columbia",
    distance: "5.8km",
    elevation: "657m",
    difficulty: "Medium",
  },
  {
    id: 12,
    imagePath: "/images/tikwalus.jpeg",
    name: "Burke North Summit",
    city: "Coquitlam",
    province: "British Columbia",
    distance: "24km",
    elevation: "1273m",
    difficulty: "Hard",
  },
  {
    id: 13,
    imagePath: "/images/needle-peak.jpeg",
    name: "Coquitlam Lake View Trail",
    city: "Coquitlam",
    province: "British Columbia",
    distance: "10.8km",
    elevation: "610m",
    difficulty: "Medium",
  },
  {
    id: 14,
    imagePath: "/images/tommhoi.jpeg",
    name: "Crown Mountain",
    city: "North Vancouver",
    province: "British Columbia",
    distance: "9.8km",
    elevation: "385m",
    difficulty: "Hard",
  },
  {
    id: 15,
    imagePath: "/images/cheam-amin.jpeg",
    name: "Mount Cheam",
    city: "Chilliwack",
    province: "British Columbia",
    distance: "9.5km",
    elevation: "700m",
    difficulty: "Medium",
  },
  {
    id: 16,
    imagePath: "/images/crest-mount-amin.jpeg",
    name: "Crest Mount",
    city: "Strathcona",
    province: "British Columbia",
    distance: "11.6km",
    elevation: "1265m",
    difficulty: "Hard",
  },
  {
    id: 17,
    imagePath: "/images/flat-iron-amin.jpeg",
    name: "Flatiron Mount",
    city: "Hope",
    province: "British Columbia",
    distance: "10km",
    elevation: "852m",
    difficulty: "Hard",
  },
  {
    id: 18,
    imagePath: "/images/frosty-mount-amin.jpeg",
    name: "Frosty Mountain",
    city: "Manning Park",
    province: "British Columbia",
    distance: "22km",
    elevation: "1160m",
    difficulty: "Hard",
  },
  {
    id: 19,
    imagePath: "/images/mount-mcGuire-amin.jpeg",
    name: "Mount McGuire",
    city: "Manning Park",
    province: "British Columbia",
    distance: "22km",
    elevation: "1160m",
    difficulty: "Hard",
  },
];
exports.seed = async function (knex) {
  await knex("hikes_list").del();
  await knex("hikes_list").insert(hikeData);
};
